mayhem
mayhemheroes/ntfs-3g pull request #1
Opened 2022-05-16 22:25 UTC by zwimer

2022-06-08 14:18 UTC, xansec requested changes
Is it necessary to add `smol.img`? Despite the name, it is 1mb in size, and will likely be truncated by Mayhem anyways without explicitly allowing it. I wonder if there is a smaller corpus file you can use.

2022-06-08 14:18 UTC, xansec commented on .github/dependabot.yml
> +version: 2
Can you comment on why this file was added?

2022-06-08 14:18 UTC, xansec commented on Dockerfile
> +CMD ["/ntfs-3g/src/ntfs-3g", "@@", "/fuzz/mount"]
This is a Mayhemfile formatted command, and will fail if run outside of Mayhem

2022-06-14 19:58 UTC, r00tus3r commented
Unfortunately, it wont be possible to use a smaller image. `ntfs-3g` is a file system driver and smallest image it can mount is 1 MB.

2022-06-15 00:48 UTC, xansec commented
Understood. Since it's already run on Mayhem, the corpus already exists (and can be referenced in the Mayhemfile). I don't see any reason to push `smol.img` to the repo itself.

2022-06-15 01:49 UTC, r00tus3r commented on Mayhemfile
> +project: mayhem-targets
Done

2022-06-15 01:49 UTC, r00tus3r commented on Dockerfile
> +FROM aflplusplus/aflplusplus
Done

2022-06-15 01:49 UTC, r00tus3r commented on Dockerfile
> +
Done

2022-06-15 01:49 UTC, r00tus3r commented on .github/dependabot.yml
> +version: 2
Removed, it was added by mistake

2022-06-15 01:50 UTC, r00tus3r commented on Dockerfile
> +RUN mkdir -p /fuzz/in
Okay, updated

2022-06-15 01:50 UTC, r00tus3r commented on Dockerfile
> +CMD ["/ntfs-3g/src/ntfs-3g", "@@", "/fuzz/mount"]
Updated

2022-06-20 19:47 UTC, r00tus3r commented
@xansec my changes in the dockerfile does not seem to be working on the mayhem server, locally it is working. And I'm not getting any useful logs from mayhem. Would you be able to take a look? Thanks!

2022-06-21 19:35 UTC, xansec commented
I was able to get this going by bumping timeout and memory limits. But I don't think this is the most effective target. I'm willing to accept it, but we may want to look into improving the efficiency of the target.
See if adding the changes I made to this run help at all:
https://mayhem.forallsecure.com/zwimer/ntfs-3g/ntfs-3g/5

2022-06-21 20:33 UTC, merged